[tools]
opentofu = "{{.OpentofuVersion}}"
terragrunt = "{{.TerragruntVersion}}"
python = "3.14.2"
awscli = "2.32.29"
terraform-docs = "0.21.0"

[env]
PROJECT_NAME = "{{.ProjectName}}"
PROJECT_VERSION = "{{.ProjectVersion}}"
TG_TF_PATH = "tofu"
TG_BACKEND_BOOTSTRAP = true
TG_PROVIDER_CACHE = 1
TG_PROVIDER_CACHE_REGISTRY_NAMES = "registry.opentofu.org"

[task_config]
dir = ".mise/tasks"
